config/routes.rb
Rails.application.routes.draw do
  resources :categories, only: [:show]

  devise_for :users,
    controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  mount Attachinary::Engine => "/attachinary"
  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :lessons, only: [:index, :show, :new, :update, :destroy, :create] do
    resources :appointments, only: [:create]
  end

  resources :appointments, only: [] do
    member do
      patch :confirm
      patch :deny
      patch :cancel
    end
  end

  resource :profile, only: [:show, :edit, :update]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/appointment.rb
class Appointment < ApplicationRecord
  belongs_to :user
  belongs_to :lesson
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :subcategories
  has_many :lessons, through: :subcategories
  has_attachment :photo
end

app/models/lesson.rb
class Lesson < ApplicationRecord
  belongs_to :subcategory
  belongs_to :user
  has_many :appointments
  has_attachment :photo
  geocoded_by :address
  after_validation :geocode

  def address
    "#{self.user.address} #{self.user.city}"
  end
end

app/models/subcategory.rb
class Subcategory < ApplicationRecord
  has_many :lessons
  belongs_to :category
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :omniauthable, omniauth_providers: [:facebook]

  has_attachment :photo
  has_many :appointments
  has_many :lessons, dependent: :destroy
  has_many :subcategories, through: :lessons
  has_many :received_appointments, source: :appointments, through: :lessons

  def self.find_for_facebook_oauth(auth)
    user_params = auth.slice(:provider, :uid)
    user_params.merge! auth.info.slice(:email, :first_name, :last_name)
    user_params[:facebook_picture_url] = auth.info.image
    user_params[:token] = auth.credentials.token
    user_params[:token_expiry] = Time.at(auth.credentials.expires_at)
    user_params = user_params.to_h

    user = User.find_by(provider: auth.provider, uid: auth.uid)
    user ||= User.find_by(email: auth.info.email) # User did a regular sign up in the past.
    if user
      user.update(user_params)
    else
      user = User.new(user_params)
      user.password = Devise.friendly_token[0,20]  # Fake password for validation
      user.save
    end

    return user
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :address, :city, :zipcode, :phone, :company_name, :profile_pic, :bio, :birthdate, :languages, :photo])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:username, :first_name, :last_name, :address, :city, :zipcode, :phone, :company_name, :profile_pic, :bio, :birthdate, :languages, :photo])
  end
end

app/controllers/appointments_controller.rb
class AppointmentsController < ApplicationController
  before_action :set_appointment, only: [:confirm, :deny, :cancel]

  def confirm
    @lesson.update!(status: "confirmed")
    redirect_to profile_path
  end

  def deny
    @lesson.update!(status: "denied")
    redirect_to profile_path
  end

  def cancel
    @lesson.update!(status: "cancelled")
    redirect_to profile_path
  end

  def create
    appt = Appointment.new(appointment_params)
    appt.user = current_user
    appt.lesson = Lesson.find(params[:lesson_id])
    appt.status = "unconfirmed"
    appt.total_price = appt.length * appt.lesson.hour_price / 60
    appt.save!
    redirect_to profile_path
  end

  private

  def appointment_params
    params.require(:appointment).permit(:date_time, :length)
  end

  def set_appointment
    @lesson = Appointment.find(params[:id])
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def show
    @category = Category.find(params[:id])
    @subcategories = @category.subcategories
    @lessons = @category.lessons.where.not(latitude: nil, longitude: nil)

    @hash = Gmaps4rails.build_markers(@lessons) do |lesson, marker|
      marker.lat lesson.latitude
      marker.lng lesson.longitude
      marker.infowindow render_to_string(partial: "/shared/map_box", locals: { lesson: lesson })
    end
  end
end

app/controllers/lessons_controller.rb
class LessonsController < ApplicationController
  def index
  end

  def show
    @lesson = Lesson.find(params[:id])
    @appointment = Appointment.new

    @hash = Gmaps4rails.build_markers(@lesson) do |lesson, marker|
      marker.lat lesson.latitude
      marker.lng lesson.longitude
      marker.infowindow render_to_string(partial: "/shared/map_box", locals: { lesson: lesson })
    end

    @lesson_coordinates = { lat: @lesson.latitude, lng: @lesson.longitude }
  end

  def new
  end

  def update
    lesson = Lesson.find(params[:id])
    lesson.update(lesson_params)
    cat = Category.find(params[:lesson][:category][:category])
    subcat = Subcategory.find(params[:lesson][:subcategory])
    lesson.save!
    redirect_to profile_path
  end

  def destroy
  end

  def create
    lesson = Lesson.new(lesson_params)
    lesson.user = current_user
    lesson.save!
    redirect_to profile_path
  end


  private

  def lesson_params
    params.require(:lesson).permit(:description, :title, :photo, :level, :hour_price, :subcategory_id)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home
  def home
    @lessons = Lesson.all
    @lesson = Lesson.new
    @subcategory = Subcategory.new
    @categories = Category.all
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  def edit
  end

  def show
    @lesson = Lesson.new
  end

  def update
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    user = User.find_for_facebook_oauth(request.env['omniauth.auth'])

    if user.persisted?
      sign_in_and_redirect user, event: :authentication
      set_flash_message(:notice, :success, kind: 'Facebook') if is_navigational_format?
    else
      session['devise.facebook_data'] = request.env['omniauth.auth']
      redirect_to new_user_registration_url
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def title(page_title)
    content_for :title, page_title.to_s
  end
end

app/views/categories/show.html.erb
<% title @category.name %>
<section class="cover height-30 imagebg parallax" data-overlay="8">
  <div class="background-image-holder">
    <%= cl_image_tag @category.photo.path %>
  </div>
  <div class="container pos-vertical-center">
    <div class="row">
      <div class="col-sm-9 col-md-12">
        <h1>
          <%= @category.name %>
        </h1>
        <div class="row">
          <% @category.subcategories.each do |subcat| %>
          <span class="btn type--uppercase"><%= subcat.name %></span>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</section>

<section>
  <div class="container">
    <div class="row">
      <%= render 'shared/list', lessons: @lessons %>
    </div>
  </div>
</section>
<div class="container">
<section>
  <div id="map" style="width: 100%; height: 600px;"></div>
</section>
</div>

<% content_for(:after_js) do %>
  <%= javascript_tag do %>
    $(document).ready(function() {
      var handler = Gmaps.build('Google');
      handler.buildMap({ internal: { id: 'map' } }, function() {
        markers = handler.addMarkers(<%= raw @hash.to_json %>);
        handler.bounds.extendWith(markers);
        handler.fitMapToBounds();
        if (markers.length == 0) {
          handler.getMap().setZoom(2);
        } else if (markers.length == 1) {
          handler.getMap().setZoom(14);
        }
      });
    });
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:200,300,400,400i,500,600,700%7CMerriweather:300,300i" rel="stylesheet">
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  <link href="http://weffle.com/css/socicon.css" rel="stylesheet">
  <link href="http://weffle.com/css/iconsmind.css" rel="stylesheet">
  <title><%= yield(:title) %></title>
  <%= csrf_meta_tags %>
  <%= action_cable_meta_tag %>
  <%= stylesheet_link_tag 'application', media: 'all' %>
</head>
<body>
  <div class="nav-container">
    <%= render 'shared/navbar' %>
  </div>
  <div class="main-container">
    <%= yield %>
    <%= render 'shared/alerts' %>
    <%= render 'shared/footer' %>
  </div>
  <%= javascript_include_tag 'application' %>
  <%= cloudinary_js_config %>
  <%= javascript_include_tag "https://maps.googleapis.com/maps/api/js?key=#{ENV['GOOGLE_MAPS_API_KEY']}" %>
  <%= javascript_include_tag "https://cdn.rawgit.com/printercu/google-maps-utility-library-v3-read-only/master/markerclusterer/src/markerclusterer_compiled.js" %>
  <%= javascript_include_tag "https://cdn.rawgit.com/printercu/google-maps-utility-library-v3-read-only/master/infobox/src/infobox_packed.js" %>

  <%= yield(:after_js) %>
</body>
</html>

app/views/lessons/_appointment_form.html.erb
<%= f.input :length, collection: [20, 30, 45, 60, 90], autofocus: true %>
<%= f. :datetime, required:true, autofocus: true %>

app/views/lessons/show.html.erb
<section class="bg--secondary space--sm">
  <div class="container">
    <div class="row">
      <div class="col-md-8 col-md-offset-2">
        <div class="boxed boxed--lg boxed--border">
          <div class="text-block text-center">
            <span class="h2"><%= @lesson.title %></span>
            <% if @lesson.photo? %>
              <%= cl_image_tag @lesson.photo.path, width: 600, crop: :fill %>
            <% elsif @lesson.user.photo? %>
            <%= cl_image_tag @lesson.user.photo.path, width: 600, crop: :fill %>
            <% else %>
            <%= image_tag "placeholder.jpg", class: "border--round", width: 900, crop: :fill %>
            <% end %>
          </div>
          <div class="text-block clearfix text-center">
            <ul class="row row--list">
              <li class="col-sm-4">
                <span class="type--fine-print block">Name:</span>
                <span class="h4"><%= "#{@lesson.user.first_name} #{@lesson.user.last_name}"%></span>
              </li>
              <li class="col-sm-4">
                <span class="type--fine-print block">Price:</span>
                <span class="h4">$<%= @lesson.hour_price %>/hour</span>
              </li>
              <li class="col-sm-4">
                <span class="type--fine-print block">Level:</span>
                <span class="h4"><%= @lesson.level %></span>
              </li>
            </ul>
          </div>
          <div class="text-block clearfix text-center">
            <ul class="row row--list">
              <li class="col-sm-4">
                <span class="type--fine-print block">Languages spoken:</span>
                <span class="h4"><%= @lesson.user.languages %></span>
              </li>
              <li class="col-sm-4">
                <span class="type--fine-print block">Company Name:</span>
                <span class="h4"><%= @lesson.user.company_name %></span>
              </li>

              <li class="col-sm-4">
                <span class="type--fine-print block">Address:</span>
                <span class="h4"><%= @lesson.user.address %></span>
                <p class="type--italic type--fine-print">
                  <%= "#{@lesson.user.city} #{@lesson.user.zipcode}" %>
                </p>
              </li>
            </ul>
          </div>
          <div class="text-block clearfix text-center">
            <ul class="row row--list">
              <li class="col-sm-12">
                <span class="type--fine-print block">Description:</span>
                <%= @lesson.description %>
              </li>
            </ul>
          </div>
          <div class="text-block clearfix text-center">
            <ul class="row row--list">
              <li class="col-sm-12">
                <span class="type--fine-print block">Bio:</span>
                <%= @lesson.user.bio %>
              </li>
            </ul>
          </div>
          <button class="btn btn--primary type--uppercase" type="submit" data-toggle="modal" data-target="#book">Book a lesson!</button>
        </div>
         <div id="map" style="width: 100%; height: 600px;"></div>
      </div>
    </div>
    <!--end of row-->
  </div>
  <!--end of container-->
</section>

<div class="modal fade container col-xs-12 col-sm-6 col-sm-offset-3" id="book">
  <section>
  <%= simple_form_for([@lesson, @appointment]) do |f| %>
  <div class="form-inputs">

         <div class="row">
            <div class="col-sm-4">
              <%= f.input :length, collection: [20, 30, 45, 60, 90], selected: 20, required:true, autofocus: true, label_html: { class: "form_label_white" } %>
              </div>
            <div class="col-sm-8">
                <%= f.input :date_time, label: "Date and time", required:true, autofocus: true, label_html: { class: "form_label_white"} %>
            </div>

  </div>

  <div class="form-actions">
    <%= f.button :submit, "Reserve!", class: "btn--primary type--uppercase" %>
  </div>
  <% end %>
</div>
  </section>
</div>

<% content_for(:after_js) do %>
  <%= javascript_tag do %>
    $(document).ready(function() {
      var handler = Gmaps.build('Google');
      handler.buildMap({ internal: { id: 'map' } }, function() {
        markers = handler.addMarkers(<%= raw @hash.to_json %>);
        handler.bounds.extendWith(markers);
        handler.fitMapToBounds();
        if (markers.length == 0) {
          handler.getMap().setZoom(2);
        } else if (markers.length == 1) {
          handler.getMap().setZoom(14);
        }
      });
    });
  <% end %>
<% end %>

app/views/pages/_categories.html.erb
<% @categories.each do |category| %>
    <div class="col-sm-2 col-xs-6">
      <%= link_to category_path(category) do %>
       <div class="block">
        <div class="feature boxed text-center imagebg" data-overlay="6">
          <div class="background-image-holder">
            <%= cl_image_tag category.photo.path %>
          </div>
          <h4 class="pos-vertical-center"><%= category.name %></h4>
        </div>
      </div>
    <% end %>
  </div>
<% end %>

app/views/pages/_list.html.erb
<% @lessons.each do |lesson| %>
<div class="col-sm-4 col-xs-6">
<%= link_to lesson_path(lesson) do %>
    <div class="feature boxed text-center imagebg" data-overlay="7">
      <div class="background-image-holder">
        <%= image_tag "yoga.jpg" %>
      </div>
      <h4 class=""><%= lesson.title %></h4>
      <h5 class=""><%= "#{lesson.user.first_name} #{lesson.user.last_name}" %> - <%= "#{lesson.subcategory.category.name}" %></h5>
      <h3 class="">$<%= lesson.hour_price %></h3>
      <h6><%= lesson.level %></h6>
    </div>
  <% end %>
</div>
<% end %>

app/views/pages/_search_bar.html.erb
<%= simple_form_for(@subcategory, url: lessons_path, method: :post) do |f| %>
          <div class="form-inputs">
            <%= f.input :category, collection: Category.all %>
          </div>

          <div class="form-actions">
            <%= f.button :submit, "Search" %>
          </div>
        <% end %>

app/views/pages/home.html.erb
<% title "Sensei - Home" %>
<section class="cover height-70 imagebg parallax" data-overlay="6">
  <div class="background-image-holder">
    <%= image_tag "background/home.jpg" %>
  </div>
  <div class="container pos-vertical-center">
    <div class="row">
      <div class="col-sm-9 col-md-12 mt--3">
        <h1 class="">
          Learn Anything from Amazing Teachers
        </h1>
        <!-- <p class="lead">
        </p> -->
        <a class="btn btn--primary type--uppercase inner-link" href="#about">
          <span class="btn__text">
            How it works
          </span>
        </a>
      </div>
    </div>
  </div>
</section>
<section class="unpad">
  <div class="row--gapless">
    <%= render "categories" %>
  </div>
</section>
<section>
  <div class="container">
    <div class="row">
      <div class="col-sm-12">
        <div class="">
          <div class="row">
            <div class="masonry__container">
              <%= render 'shared/list', lessons: @lessons %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>
<section id="about" class="text-center">
  <div class="container">
    <div class="row">
      <div class="col-sm-10 col-md-8">
        <h2>About Studiate</h2>
        <p class="lead">
         We at Studiate believe that it is important that you keep learning throughout your live and that the things you learn define you as a person. But we also understand that it is sometimes difficult do get started because you don't now where to begin. Would you agree that it would nice if you had someone to help you get started? Someone like a teacher?
        </p>
        <p class="lead">
          Studiate gives everyone the possibiltiy to learn with the help of a amazing teacher. At Studiate you can find and book a skilled teacher near you.
          You make an account and search by category for a teacher. When you found a teacher you like, you make an appointment and the teacher will automatically receive your booking. After receiving the booking, the teacher will contact you using your personal information in your profile. It is that simple!
        </p>
      </div>
    </div>
    <!--end of row-->
  </div>
  <!--end of container-->
</section>

app/views/profiles/_appointments.html.erb
 <% current_user.appointments.each do |appointment| %>
 <div class="col-sm-6">
  <div class="feature boxed boxed--border">
    Lesson with <a><%= appointment.lesson.user.first_name %></a>
    <h5><%= appointment.date_time.to_formatted_s(:short) %></h5>
    <ul>
      <li class="li">Length: <%= appointment.length %></li>
      <li class="li">Total price: <%= appointment.total_price %></li>
      <li class="li">Status:  <%= appointment.status %></li>
      <%= link_to "Cancel Appointment", cancel_appointment_path(appointment), method: :patch %>
    </ul>
  </div>
</div>
<% end %>

<% current_user.received_appointments.each do |appointment| %>
<div class="col-sm-6">
  <div class="feature boxed boxed--border">
    Lesson with <a><%= appointment.user.first_name %></a>
    <h5><%= appointment.date_time.to_formatted_s(:short) %></h5>
    <ul>
      <li class="li">Length: <%= appointment.length %></li>
      <li class="li">Total price: <%= appointment.total_price %></li>
      <li class="li">Status:  <%= appointment.status %></li>
      <% unless appointment.status == "confirmed" || appointment.status == "denied" %>
      <%= link_to "Confirm", confirm_appointment_path(appointment), method: :patch %> |
      <%= link_to "Deny", deny_appointment_path(appointment), method: :patch %>
      <% end %>
      <% unless appointment.status == "cancelled" || appointment.status == "denied" %> |
      <%= link_to "Cancel", cancel_appointment_path(appointment), method: :patch %>
      <% end %>
    </ul>
  </div>
</div>
<% end %>

app/views/profiles/_lesson_form.html.erb
<div class="row">
  <div class="col-sm-12">
    <%= f.input :title, label: false, placeholder: "Lesson headline", required: true %>
  </div>
  <div class="col-sm-12">
    <%= f.input :description, label: false, placeholder: "Type a description here", required: true %>
  </div>
  <div class="col-sm-6">
    <%= f.input :hour_price, label: false, placeholder: "Hour price", required: true %>
  </div>
  <div class="col-sm-6">
    <%=  f.simple_fields_for :category do |y| %>
      <%= y.input :category, collection: Category.all, selected: Category.first, required: true, label: false, autofocus: true %>
    <% end %>
  </div>
  <div class="col-sm-6">
    <%= f.association :subcategory, placeholder: "subcategory", label: false, collection: Subcategory.all %>
  </div>
  <div class="col-sm-6">
     <div class="btn btn-primary new_subcategory">Add new subcategory</div>
  </div>
  <div class="col-sm-6 sub hidden">
     <%= f.input :subcategory, label: false, required: true, autofocus: true %>
  </div>
  <div class="col-sm-12">
      <%= f.input :level, label: false, placeholder: "level", required: true, autofocus: true %>
  </div>
  <div class="col-sm-12">
    <%= f.input :photo, label: false, as: :attachinary %>
  </div>
</div>

app/views/profiles/_lessons.html.erb
<% current_user.lessons.each do |lesson| %>
<div class="boxed boxed--lg boxed--border">
  <div class="text-block">
    <div class="heading-block">
      <h4>Lessons offered</h4>
    </div>
  </div>
  <div class="text-block clearfix text-center">
    <% if lesson.photo? %>
    <%= cl_image_tag lesson.photo.path, width: 1200, crop: :fill %>
    <% end %>
    <ul class="row row--list">
      <li class="col-sm-4">
        <span class="type--fine-print block">Title:</span>
        <span class="h4"><%= lesson.title %></span>
      </li>
      <li class="col-sm-4">
        <span class="type--fine-print block">Price:</span>
        <span class="h4">$<%= lesson.hour_price %>/hour</span>
      </li>
      <li class="col-sm-4">
        <span class="type--fine-print block">Level:</span>
        <span class="h4"><%= lesson.level %></span>
      </li>
      <li class="col-sm-12">
        <span class="type--fine-print block">Description:</span>
        <%= lesson.description %>
      </li>
    </ul>
  </div>
  <div class="col-sm-6">
    <button class="btn btn--primary type--uppercase" type="submit" data-toggle="modal" data-target="#update_lesson">Update lesson</button>
  </div>
  <div class="col-sm-6">
    <button class="btn btn--primary type--uppercase" type="submit" data-toggle="modal" data-target="#add_lesson">Add lesson</button>
  </div>
</div>
<% end %>

<div class="modal fade container col-xs-12 col-sm-6 col-sm-offset-3" id="add_lesson">
  <section>
    <%= simple_form_for(@lesson, url: lessons_path, method: :post) do |f| %>
    <div class="form-inputs">
      <%= render 'lesson_form', f: f %>
    </div>

    <div class="form-actions">
      <%= f.button :submit, "Add" %>
    </div>
    <% end %>
  </section>
</div>

app/views/profiles/_profile_form.html.erb
         <div class="row">
            <div class="col-sm-6">
              <%= f.input :first_name, label: false, placeholder: "First Name", required: true %>
            </div>
            <div class="col-sm-6">
              <%= f.input :last_name, label: false, placeholder: "Last Name", required: true %>
            </div>
            <div class="col-sm-12">
              <%= f.input :email, label: false, placeholder: "Email", required: true %>
            </div>
            <div class="col-sm-12">
              <%= f.input :phone, label: false, placeholder: "Phone", required: true %>
            </div>
            <div class="col-sm-12">
              <%= f.input :birthdate, label_html: { class: "form_label_white" }, wrapper_html: { class: "text-center" } %>
            </div>
            <div class="col-sm-6">
               <%= f.input :password, label: false, placeholder: "Password", required: true %>
            </div>
            <div class="col-sm-6">
               <%= f.input :password_confirmation, label: false, placeholder: "Confirm your Password", required: true %>
            </div>
            <div class="col-sm-12">
              <%= f.input :photo, as: :attachinary, label: false %>
            </div>
            <div class="col-sm-12">
              <%= f.input_field :teacher, inline_label: true, label: false, as: :boolean, wrapper_html: { class: "teacher-toggle form_label_white" } %>
            </div>
            <div class="col-sm-12">
              <%= f.input :bio, label: false, placeholder: "Bio", wrapper_html: { class: 'teacher hidden' } %>
            </div>
            <div class="col-sm-12">
              <%= f.input :languages, label: false, placeholder: "Languages", wrapper_html: { class: 'teacher hidden' } %>
            </div>
            <div class="col-sm-12">
              <%= f.input :address, label: false, placeholder: "Address", wrapper_html: { class: 'teacher hidden' } %>
            </div>
            <div class="col-sm-12">
              <%= f.input :zipcode, label: false, placeholder: "Zipcode", wrapper_html: { class: 'teacher hidden' } %>
            </div>
            <div class="col-sm-12">
              <%= f.input :company_name, label: false, placeholder: "Company Name", wrapper_html: { class: 'teacher hidden' } %>
            </div>
            <div class="col-sm-12">
              <%= f.input :city, label: false, placeholder: "City", wrapper_html: { class: 'teacher hiddenl' } %>
            </div>
          </div>

app/views/profiles/show.html.erb
<!-- profile information: address etc
 -->
<%= render 'profile_info' %>

<%= content_for(:after_js) do %>
  <script>
    $(document).ready(function() {
      $('.new_subcategory').on('click', function(event){
       $('.sub').removeClass('hidden');
      });
    });
  </script>
<% end %>

app/views/profiles/updateSubcategories.html.erb
<%= simple_form_for @lesson, html: {class: 'form-horizontal'} do |f| %>

<%= f.association :subcategory, collection: @subcategories, input_html: { data: {update_subcategories: "true", remote: :true, url: "/update_subcategories"} } %>

<% end %>

app/views/shared/_alerts.html.erb
<% if notice %>
<div class="notification pos-right pos-top col-sm-4 col-md-3" data-animation="from-top" data-autoshow="100">
  <div class="boxed boxed--border border--round box-shadow">
    <div class="text-block">
      <h5>Notice</h5>
      <p>
        <%= notice %>
      </p>
    </div>
  </div>
</div>
<% end %>

<% if alert %>
<div class="notification pos-right pos-top col-sm-4 col-md-3" data-animation="from-top" data-autoshow="100">
  <div class="boxed boxed--border border--round box-shadow">
    <div class="text-block">
      <h5>Error!</h5>
      <p>
        <%= alert %>
      </p>
    </div>
  </div>
</div>
<% end %>

app/views/shared/_list.html.erb
<% @lessons.each do |lesson| %>
<div class="col-xs-12 col-md-6 col-lg-4 masonry__item">
  <div class="card card-2 text-center mb--1 box-shadow">
    <div class="card__top">
      <a href="#">
        <% if lesson.photo %>
        <%= cl_image_tag lesson.photo.path %>
        <% elsif lesson.user.photo %>
        <%= cl_image_tag lesson.user.photo.path, width: 360, height: 220, crop: :thumb, gravity: :face %>
        <% end %>
      </a>
    </div>
    <div class="card__body">
      <span class="h4"><%= lesson.title %></span>
      <%= link_to lesson_path(lesson) do %>
      <button class="btn btn--primary type--uppercase" type="submit">Learn More</button>
      <% end %>
    </div>
    <div class="card__bottom text-center">
      <div class="card__action">
        <span class="type--fade">Name</span>
        <span class="h5"><%= "#{lesson.user.first_name} #{lesson.user.last_name}" %></span>
      </div>
      <div class="card__action">
        <span class="type--fade">Category</span>
        <span class="h5"><%= "#{lesson.subcategory.category.name}" %></span>
      </div>
      <div class="card__action">
        <span class="type--fade">Pice</span>
        <span class="h5">$<%= lesson.hour_price %>/hour</span>
      </div>
      <div class="card__action">
        <span class="type--fade">Level</span>
        <span class="h5"><%= lesson.level %></span>
      </div>
    </div>
  </div>
</div>
<% end %>

app/views/shared/_map_box.html.erb
<%= link_to lesson_path(lesson) do %>
<h4><%= lesson.title %></h4>
<p><%= lesson.user.first_name + " " + lesson.user.last_name %></p>
<p>Hour price: <%= lesson.hour_price %></p>
<% if lesson.photo? %>
  <%= cl_image_tag lesson.photo.path, width: 210, height: 150, crop: :fill, gravity: :face %>
<% else %>
  <%= cl_image_tag lesson.user.photo.path, width: 210, height: 150, crop: :fill, gravity: :face %>
<% end %>
<% end %>